### ISSUE TITLE
Update for macOS catalina

### ISSUE THREAD

**Issue by AlexGh12** [fabriziocucci/git-bash-for-mac#10]
Hi, I just updated to macOS Catalina and it doesn't work as before, there are no colors, it's just white.

![Captura de Pantalla 2019-11-09 a la(s) 10 27 55](https://user-images.githubusercontent.com/13667952/68531809-ecabd900-02db-11ea-99bd-7ec95ab095e7.png)

In the repository folder remains the same, does not show the branch or anything

![Captura de Pantalla 2019-11-09 a la(s) 10 32 32](https://user-images.githubusercontent.com/13667952/68531861-8ffcee00-02dc-11ea-9f92-40adf01fd412.png)

help me!!

**Comment by AviParikh** [comment]
I'm having this same problem in mojave

**Comment by Ondkloss** [comment]
I'm guessing you are using `zsh` instead of `bash`. While this project could probably use a `zsh`-version, I think changing the default shell to `bash` should probably give you the correct appearance:

    chsh -s /bin/bash

**Comment by xamoko** [comment]
> I'm guessing you are using `zsh` instead of `bash`. While this project could probably use a `zsh`-version, I think changing the default shell to `bash` should probably give you the correct appearance:
> 
> ```
> chsh -s /bin/bash
> ```

i cant use this :(

**Comment by Ondkloss** [comment]
> i cant use this :(

Any input on why you can't use it? 

I [made a fork](https://github.com/ondkloss/git-bash-for-mac) of this which also provides config for `zsh`. You could try to `install.sh` it if you want to try using it with `zsh` instead of going back to `bash`.
