### ISSUE TITLE
Installation doesn't work properly if .bash_profile does not end with newline

### ISSUE THREAD

**Issue by danniefraim** [fabriziocucci/git-bash-for-mac#3]
If .bash_profile contains data but does not end with a newline, the installation does not work, because the script will just append to the end of the last line in the file:

```
Last login: Thu Aug 30 09:43:14 on ttys001
-bash: export: `/Users/danni/.git-bash-for-mac.sh': not a valid identifier
Danni-Efraims-MacBook-Pro:~ danni$ cat ~/.bash_profile
export LC_ALL=sv_SE.UTF-8
export LANG=sv_SE.UTF-8source ~/.git-bash-for-mac.sh
```

I will submit a pull request that fixes this.

**Comment by fabriziocucci** [comment]
@danniefraim thanks a lot for this! :)
