### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by crjacinro** [fabriziocucci/git-bash-for-mac#5]
.bash profile: No such file or directory after running install script.

**Comment by fabriziocucci** [comment]
Hi @crjacinro, a couple of questions to figure out what's going on here:
* are you using the default Mac `Terminal`?
* can you see the file `.bash_profile` under your user directory?

**Comment by crjacinro** [comment]
Found a workaround. Thanks :-)

**Comment by darrensw777** [comment]
> Found a workaround. Thanks :-)

Care to share? Same problem
